"""team name not nullable

Revision ID: ea2b97c97b55
Revises: 8c1b0067412f
Create Date: 2023-05-21 11:36:07.850828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea2b97c97b55'
down_revision = '8c1b0067412f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('slack_organizations', 'team_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('slack_organizations', 'team_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
