name: Build and Test
on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches:
      - main
    paths:
      - 'applications/backend/**'
  push:
    branches:
      - main
    paths:
      - 'applications/backend/**'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.13
      - name: Install dependencies
        working-directory: applications/backend
        run: pip install -r applications/backend/requirements.txt
      - name: Install test dependencies
        working-directory: applications/backend
        run: pip install -r applications/backend/requirements-test.txt
      - name: Run Pytest
        working-directory: applications/backend
        run: pytest tests
